STEP 1: Import Required Libraries

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

 STEP 2: Import the Dataset

In [58]:
ds = pd.read_csv(r"C:\Users\hp\Desktop\AI\data.csv")
ds

,States,Age,Salary,Purchased
0,Texas,44.0,72000.0,No
1,Florida,27.0,48000.0,Yes
2,California,30.0,54000.0,No
3,Texas,38.0,61000.0,No
4,California,NaN,65000.0,Yes
5,Texas,35.0,58000.0,Yes
6,California,40.0,NaN,No
7,Texas,48.0,79000.0,Yes
8,Florida,50.0,83000.0,No
9,Texas,37.0,67000.0,Yes


STEP 3: Explore the Dataset

In [59]:
# Display the first 5 rows
print(ds.head())

# Display the number of rows and columns
print(ds.shape)

# Display column names and data types
print(ds.info())

       States   Age   Salary Purchased
0       Texas  44.0  72000.0        No
1     Florida  27.0  48000.0       Yes
2  California  30.0  54000.0        No
3       Texas  38.0  61000.0        No
4  California   NaN  65000.0       Yes
(10, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   States     10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes
None


In [60]:
# Check for missing values
print(ds.isnull().sum())

States       0
Age          1
Salary       1
Purchased    0
dtype: int64


STEP 4: Separate Features (X) and Target (y)

In [61]:
X = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [62]:
X

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', nan, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, nan],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [63]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [64]:
# Handling missing values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [65]:
X

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', 38.77777777777778, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, 65222.22222222222],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [66]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

STEP 5: Encode Categorical Data

In [67]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encode', OneHotEncoder(), [0])] , remainder = 'passthrough')
X = ct.fit_transform(X)

In [68]:
X

array([[0.0, 0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 0.0, 1.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 37.0, 67000.0]], dtype=object)

In [69]:
X = X[: , 1:] # avoinding the dummy variable trap

In [70]:
X

array([[0.0, 1.0, 44.0, 72000.0],
       [1.0, 0.0, 27.0, 48000.0],
       [0.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 1.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 37.0, 67000.0]], dtype=object)

STEP 6: Split Dataset into Training and Testing Sets

In [71]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
x_train

array([[0.0, 1.0, 35.0, 58000.0],
       [0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 48.0, 79000.0],
       [0.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 37.0, 67000.0],
       [0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 40.0, 65222.22222222222]], dtype=object)

STEP 7: Feature Scaling

In [80]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [79]:
x_train

array([[ 0.        ,  0.77459667, -0.7529426 , -0.97016068],
       [ 0.        ,  0.77459667,  1.00845381,  0.92871692],
       [ 0.        ,  0.77459667,  1.79129666,  1.87815573],
       [ 0.        , -1.29099445, -1.73149616, -1.51269714],
       [ 0.        ,  0.77459667, -0.36152118,  0.25054635],
       [ 0.        , -1.29099445, -0.01359102, -0.02072188],
       [ 0.        ,  0.77459667, -0.16581046, -0.56325834],
       [ 0.        , -1.29099445,  0.22561096,  0.00941904]])